### ISSUE TITLE
Error in post-command-hook (spotlight--post-command): (void-variable spotlight--colors)

### ISSUE THREAD

**Issue by tsdh** [Malabarba/beacon#1]
Right now, `spotlight-mode` is immediately deactivated because of the error in the subject.  The problem is that `spotlight-blink` contains `(length spotlight--colors)` but `spotlight--colors` is not defined.  I guess that's an artifact of an older version and the expression should be changed to `spotlight-size`.

**Comment by Malabarba** [comment]
Indeed. Thanks for catching that.
