### ISSUE TITLE
Beacon-mode not working after starting Emacs

### ISSUE THREAD

**Issue by ReneFroger** [Malabarba/beacon#10]
## Setup:
GUI version GNU Emacs 25.0.50.1 (x86_64-w64-mingw32)
of 2015-07-25 on KAEL

[Compiled from EmacsW64.](http://emacsbinw64.sourceforge.net/)

Beacon, using the latest version of Beacon from MELPA

Windows 7 x64 bit.

## Situation:

Thanks for creating this package! I use the `use-package`, and I configured beacon as following:  

    (use-package beacon
        :config
        (setq beacon-mode 1)
        (setq beacon-blink-delay 0.2)
        (setq beacon-blink-duration 0.2)
        (setq beacon-blink-when-point-moves 7)
        (setq beacon-blink-when-window-changes nil)
        (setq beacon-blink-when-window-scrolls nil)
        (setq beacon-color "brown")
        (setq beacon-push-mark 5)
        (setq beacon-size 25)
    )

In my dot-Emacs. When I start Emacs, and move around with the cursor, I don't see the beacon. When I disable the beacon-mode and enable it again, then I'll see the beacon. I find that weird, given the fact that beacon-mode is already enabled on startup.

![beacon](https://cloud.githubusercontent.com/assets/5211845/10558922/c019678a-74e2-11e5-9225-33d09c0758fe.gif)

Perhaps a bug?

**Comment by Malabarba** [comment]
RTM. 😉
That's not how you activate the mode. 

Use (beacon-mode 1) Instead of (setq beacon-mode 1).

**Comment by ReneFroger** [comment]
Ah, that's it. I find it weird that the beacon-mode is enabled on startup (or it would not be disabled when you call the command `beacon-mode` anyway).

Thanks for your help.

**Comment by Malabarba** [comment]
I don't quite understand. What do you mean by "beacon-mode is enabled on startup"? 

It's only enabled if you turn it on with `(beacon-mode 1)`.

**Comment by ReneFroger** [comment]
See the animation. When I call `beacon-mode`, you see in the minibuffer the message that `beacon-mode` is disabled. So it was enabled earlier on startup.

**Comment by Malabarba** [comment]
I see your confusion. That's just emacs being silly. 
When you invoke a minor mode interactively, Emacs decides what to do based on the mode variable. Since you had set the mode variable to 1, Emacs thinks that the mode is currently active (even though it isn't) and then tries to deactivate it.
