### ISSUE TITLE
Flickering Cursor

### ISSUE THREAD

**Issue by compunaut** [Malabarba/beacon#11]
Thank you for this package it's really a nice visual extension :)

I have one problem:
Sometimes the cursor is flickering while the effect is in action. Do you have the same behaviour on your side?

**Comment by Malabarba** [comment]
No, that shouldn't happen. Do you think you can narrow down the situation where it's happening?

**Comment by hatschipuh** [comment]
It happens all the time, only sometimes not. I have recorded it, the following is a video file, Github supports only image files so I uploaded it as an png hope it works and you can download and watch it.


![nosound](https://cloud.githubusercontent.com/assets/13802849/10561765/2d01195a-7539-11e5-91be-88904d7a0bd1.png)

**Comment by Malabarba** [comment]
I see. That might be a redisplay bug. =/

Could you try the followiung?

  * start Emacs with `emacs -Q`, 
  * load the `seq.el` file
  * load the `beacon.el` file
  * Try to reproduce this again.

Does it happen?

**Comment by hatschipuh** [comment]
Yes, it still happens. I'm on Linux. I don't know what redisplay bug means. If you have ideas how I could investigate further let me know, thanks for the help.

**Comment by Malabarba** [comment]
Redisplay is basically when Emacs draws the screen.

Here's one more thing to try. Evaluate the following code:

    (defun redisplay-command ()
      (interactive)
      (redisplay))
    (global-set-key [f6] #'redisplay-command)

This makes it so that `F6` triggers a redisplay. Ideally, this should have no visual effect. 
Hit `F6` a few times while paying attention to the cursor. Try to see if the cursor flickers at any moment.

**Comment by hatschipuh** [comment]
Just tried it, the cursor is not flickering on redisplay.

**Comment by Malabarba** [comment]
Ok, one more thing to try. 

1. Disable `beacon-mode`
2. Hit `M-:` and type `(beacon--shine)`, this will leave a permanent beacon at point.
3. *Without moving the cursor*, hit `F6` several times and see if the cursor flickers.

**Comment by hatschipuh** [comment]
No it does not flicker in this case. I already get used to the flickering ,maybe I should consider it a feature ;)

**Comment by Malabarba** [comment]
Something else just occurred to me. This could be due to the beacon
animation happening so fast than redisplay can't keep up. So maybe slowing
down the animation will help.
You can do that by decreasing beacon-size or
increasing beacon-blink-duration.

**Comment by hatschipuh** [comment]
Thanks, indeed with a value of 0.8 for beacon-blink-duration the problem disappears.

Do you have an idea why my redisplay is to slow? Seems to work for others. I thought maybe it is something with evil mode and using different cursor styles but the problem occurs when I disable evil-mode, as well.

**Comment by Malabarba** [comment]
It could be that redisplay is doing too much work, but there could be many different causes for that. 
Try turning on the profiler with M-x profiler-start. Then evaluate (dotimes (i 50) (redisplay)) in the scratch buffer, and finally do M-x profiler-report.

**Comment by hatschipuh** [comment]
Thanks I didn't knew about that! Very useful, although I can not find the cause. Will report it here if I find it.
