### ISSUE TITLE
Blinking when hl-line-mode is on

### ISSUE THREAD

**Issue by dpathakj** [Malabarba/beacon#12]
The default value for `beacon-dont-blink-predicates` includes this line: 

`(add-hook 'beacon-dont-blink-predicates (lambda () (bound-and-true-p hl-line-mode)))`

This makes it harder than it needs to be to combine blinking with hl-line-mode (no way to `remove-hook`). Is there a deep reason for this? When I `(setq beacon-dont-blink-predicates)` and turn on `hl-line-mode` things seem to work fine.

I can see a few ways to change this.
- completely remove this predicate
- add a variable, `beacon-disable-for-hl-line-mode`, and change the predicate to `(lambda () (and beacon-disable-for-hl-line-mode (bound-and-true-p hl-line-mode)))`, so that changing this behavior is as simple as `(setq beacon-disable-for-hl-line-mode nil)`
- bind the predicate to a function, so that `remove-hook` works

thanks for writing this, by the way--it's useful.

**Comment by Malabarba** [comment]
Did you try this? 

    (remove-hook 'beacon-dont-blink-predicates (lambda () (bound-and-true-p hl-line-mode)))

I thought it would work. 

> Is there a deep reason for this? 

No big reason. 
I just thought it would sort of conflict conceptually, since both packages are highlighting the cursor position. 

I can probably remove it.

**Comment by dpathakj** [comment]
That doesn't work. Advice I've seen elsewhere is to bind hook functions to names, and add/remove the names. Fwiw, here's what `beacon-dont-blink-predicates` looks like after beacon is loaded:

```elisp
(window-minibuffer-p
 #[0 "\301\300!\205\207"
     [hl-line-mode boundp]
     2 "\n\n(fn)"])
```

I think the difference is that beacon.el was compiled. See http://stackoverflow.com/a/22671324

If I `(add-hook 'beacon-dont-blink-predicates (lambda () (bound-and-true-p hl-line-mode)))` at *runtime*, I get a third argument that is removable by the code you paste.

**Comment by Malabarba** [comment]
Yeah that makes sense. It's definitely the byte-compilation. 
I'll just remove that function from the hook.

**Comment by dpathakj** [comment]
Thanks!

**Comment by sshbio** [comment]
It seems that beacon now works with hl-line on.

However, with the default (white) theme, as an example, with hl-line on, the "background color" of beacon is white, but the hl-line is light green.

Maybe the beacon colors could be a range of the chose customized color to the hl-line if activated or to the default face's background color if not?

It seems that this could be done at [this line](https://github.com/Malabarba/beacon/blob/00920450d83ffe7a02bbe98997e266726819efc2/beacon.el#L238) by replacing `(face-attribute 'default :background)` by a `if` ?

Anyway, this is a funny little package that I like!

**Comment by Malabarba** [comment]
> However, with the default (white) theme, as an example, with hl-line on, the "background color" of beacon is white, but the hl-line is light green.

Yes, I've noticed this on dark themes too. 

>Maybe the beacon colors could be a range of the chose customized color to the hl-line if activated or to the default face's background color if not?

That might be OK, but I'd prefer a more general solution. Instead of doing `(face-attribute 'default :background)`,  beacon should check the background color at point. This would automatically work with hl-line-mode and many other packages that do similar stuff.

**Comment by sshbio** [comment]
Well, it would be a real improvement that could be applied to many other situations, so maybe we can [find tools](http://www.emacswiki.org/emacs/download/eyedropper.el) for this.

**Comment by Malabarba** [comment]
Actually, a comment in that link pointed me to background-color-at-point. :-)

**Comment by sshbio** [comment]
Marvellous! :)
