### ISSUE TITLE
beacon-blink: Symbol's function definition is void: seq-find 

### ISSUE THREAD

**Issue by alphapapa** [Malabarba/beacon#13]
This looks really cool.  I just installed it from MELPA, but it's not working, and I see this in the messages:
```
beacon-blink: Symbol's function definition is void: seq-find [7 times]
Error in post-command-hook (beacon--post-command): (void-function seq-find)
```
I upgraded the `seq` package and now it works.  I guess that function was added in the last few months.

**Comment by Malabarba** [comment]
Try updating your seq version.

**Comment by alphapapa** [comment]
Yes, I mentioned that.  :)  I thought maybe you'd want to mention the minimum version or something in the readme.

**Comment by Malabarba** [comment]
The minimum version is stayed in the package headers. 
I strongly recommend you delete your seq package from Melpa and install it from gnu. 
Melpa is notoriously messy with version numbers, and that's particularly problematic with dependency libs like seq or dash.

**Comment by alphapapa** [comment]
Oh, I see.  Thanks.
