### ISSUE TITLE
Flash beacon when emacs gains foucs

### ISSUE THREAD

**Issue by aecay** [Malabarba/beacon#14]
It would be good to have an option to flash a beacon when switching focus from another program to emacs.

**Comment by Malabarba** [comment]
Indeed, sounds very reasonable. 👍

**Comment by Malabarba** [comment]
And by the way, PRs welcome. :-)

**Comment by aecay** [comment]
I will give it a shot when I have some time.  (But of course anyone else is welcome to swoop in ahead of me.)

**Comment by Malabarba** [comment]
Emacs now has hooks for focus change, so it might just be as simple as adding beacon-blink to this hook.

**Comment by Malabarba** [comment]
Ok, I've implemented this, but it's off by default because it's unreliable on some systems.

**Comment by aecay** [comment]
I didn't know about `focus-in-hook`; I thought it was going to involve some mucking around with keymaps and events.  I'm glad it turned out to be easier -- and thanks for doing it!  I'm really loving beacon over the past couple days I've been using it.
