### ISSUE TITLE
Odd issues with becaon and info

### ISSUE THREAD

**Issue by aecay** [Malabarba/beacon#15]
I've noticed two issues when using info buffers with beacon enabled:

1. The beacon flashes when using `C-p` to move the cursor from the node title to the preceding blank line.  This happens irrespective of the setting of `beacon-blink-when-point-moves`.
2. Pressing `C-p` again to move to the node name causes a strange delay (~2-3 s on my machine), and a beacon overlay which is a solid color across the entire line.  This occurs only if `beacon-blink-when-point-moves` is set to an integer (values I tried were 1 and 20).

This is on an X11 frame running under linux with a recent-ish emacs git master.  Steps to reproduce:

0. Activate beacon mode
1. C-h i
2. m Elisp RET
3. C-n
4. C-p (triggers point 1)
5. C-p (triggers point 2, if `b-b-w-p-m` is set appropriately)

**Comment by Malabarba** [comment]
Thanks for reporting. :+1: I'll look into this when I get a moment.

**Comment by tsdh** [comment]
I've debugged point 1 just now.  The blink is caused by `beacon--window-scroll-function`, and the `this-command` is nil case applies.  I have totally no clue why `window-scroll-functions` are run when point moves from an info heading upwards even when that causes no window scroll.

I can't reproduce the delay, though.  This might be caused by `beacon--movement->` being slow in large buffers due to its use of `count-screen-lines`.

**Comment by Malabarba** [comment]
Thanks Tassilo. I've also noticed something similar elsewhere. It looks like we can't rely on the hook being called only when there was a visible scroll.

**Comment by aecay** [comment]
I've checked and Tasssilo is correct about `count-screen-lines` -- commenting out that function in `beacon--movement-<` causes the delay to disappear.  I'm not sure what the alternative would be though, if `count-screen-lines` is known to be slow.

**Comment by Malabarba** [comment]
@aecay Tassilo already wrote an improvement for that, I just haven't pushed it to Elpa yet. So at least this problem will be gone soon. ;-)

**Comment by Malabarba** [comment]
By the way, while we don't have a fix for the info bug. You can disable it info-mode with `beacon-dont-blink-major-modes`
