### ISSUE TITLE
calfw compatibility

### ISSUE THREAD

**Issue by csantosb** [Malabarba/beacon#17]
Thinking about [calfw](https://github.com/kiwanami/emacs-calfw), `beacon-blink-when-point-moves` is very handy with respect to vertical movement, but, would it be possible to get the equivalent for columns (horizontal movement) ?
Great package, really useful, thanks !

**Comment by Malabarba** [comment]
Sounds reasonable. PRs welcome. :-)

**Comment by csantosb** [comment]
Done.
