### ISSUE TITLE
Load time

### ISSUE THREAD

**Issue by andschwa** [Malabarba/beacon#18]
I load Beacon via `use-package`:

```elisp
(use-package beacon)
```

Which takes a while!

```
Loading package beacon...done (5.682s)
```

Loading the beacon package (not even enabling the mode) appears to take 5 to 7 seconds on my 2.5 GHz Intel Core i5.

I'd like to use it, but that addition to Emacs' init time is... too much. Any ideas?

**Comment by Malabarba** [comment]
Oh dear, that shouldn't happen.
Have you tried the profiler?

Replace that line with something like this:

    (profiler-start 'cpu)
    (use-package beacon)
    (profiler-report)
    (profiler-stop)

and you should get a report when it runs

**Comment by pennersr** [comment]
Same issue:

- normal-top-level                                               3016  99%
 - command-line                                                  3016  99%
  - funcall                                                      3016  99%
   - #<compiled 0x41230075>                                      3016  99%
    - #<compiled 0x4009b0f7>                                     3016  99%
     - load                                                      3016  99%
      - load-with-code-conversion                                3016  99%
       - eval-buffer                                             3016  99%
        - require                                                3003  98%
         - byte-code                                             3003  98%
          - custom-declare-variable                              2999  98%
           - custom-initialize-reset                             2999  98%
            - byte-code                                          2999  98%
             - eval                                              2999  98%
              - funcall                                          2999  98%
               - #<compiled 0x42e0a873>                          2999  98%
                  char-displayable-p                             2994  98%
          - require                                                 1   0%
           - file-truename                                          1   0%
              file-truename                                         1   0%
          profiler-start                                           10   0%
        - profiler-report                                           1   0%
         - profiler-report-cpu                                      1   0%
            profiler-cpu-profile                                    1   0%
- ...                                                              24   0%
   Automatic GC                                                    24   0%

**Comment by Malabarba** [comment]
Thanks. The problem is clearly with char-displayable-p. I guess I'll just have to remove it.

**Comment by andschwa** [comment]
Confirmed, fixed it. Thanks!
