### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by tsdh** [Malabarba/beacon#2]
After fixing #1 locally, I'm now using spotlight for about half an hour and basically I like it.  However, there are some improvements you might want to consider.

1. I think it would be more visually appealing and intuitive if the spotlight highlight would extend to the left and the right instead of only to the right, e.g., the character under point would be in the spotlight and the neighboring characters a bit less so.  I guess that should be configurable because in the end someone will want a cross-hair spotlight or a spotlight spiral.

2. Spotlighting doesn't work when point is on an empty line or at the end of a line.  Suggestion 1 would at least improve the end-of-line situation, too.  But I think you can't do much about the empty lines problems (although this situation is covered by the code and contains a commented funcall `(spotlight--after-string)`...

**Comment by tsdh** [comment]
Oh, and I just found out that spotlight slows down `beginning-of-buffer`/`end-of-buffer` and `isearch` considerably in large buffers because it always computes the number of screen lines between the previous place and point.  I think it would be better if `spotlight-minimum-distance` specified the distance in terms of characters instead of lines.  That could be checked with just subtraction instead of the costly `count-screen-lines`.

An additional (tho less important) performance consideration is not to create the timer with `run-at-time` for every blink but instead do it just once and restart the canceled timer thereafter with `timer-activate`.

**Comment by Malabarba** [comment]
First of all, thanks for alpha testing. 

1. Yes. I'd like to at least offer the option of different shapes. The current version is just a first draft. 

2. The end-of-line thing is a known bug. I know how to fix it, it's just going to be a bit of work. 

3. I didn't know about the slow down problem. I'll figure out a way around it, probably by doing some rough estimate before doing the expensive count. I can't completely abdicate of counting screen lines, because in org-mode it's very common to move 1 screen line while moving point thousands of characters.

**Comment by tsdh** [comment]
Ok, great. Wrt. 3 I think it would make sense to spotlight only if the window has been scrolled which can be easily checked by remembering and comparing `window-start ` and `window-end`. I mean, when there's no scrolling, the chances that I loose track of point is pretty low.

**Comment by Malabarba** [comment]
That's a good idea. I'll experiment with that too.

**Comment by Malabarba** [comment]
The current version uses scrolling and not buffer movement by default. Currently seems to work well.
The only disadvantage is that I'm forced to trigger a `redisplay` because sometimes the window scrolls *after* `post-command-hook` has run.

**Comment by tsdh** [comment]
Seems to work nicely. Thanks!

**Comment by fhaun** [comment]
Very nice. How can I disable it when using Gnus?

**Comment by Malabarba** [comment]
@fhaun I'll implement some way of disabling it before I push it to Elpa tomorrow. It'll probably be a couple of simple variables.

**Comment by Malabarba** [comment]
@fhaun since latest push, you can specify major-modes where it should be disabled (see readme).

**Comment by fhaun** [comment]
Ah ok, thats sounds very good. Thanks!
