### ISSUE TITLE
Does not "shine" when doing C-l (recenter-top-bottom)

### ISSUE THREAD

**Issue by Knusper** [Malabarba/beacon#20]
When recentering the screen on the cursor at the center, top or bottom of the window the beacon should shine - since the content of the window changes, since we move in the file, and the position of the cursor changes. At least it appears illogical, why it does not shine in this case....

**Comment by Malabarba** [comment]
I disabled it by default because I found it rather distracting (I never lose my cursor with the `C-l` command).

You can enable it by configuring `beacon-dont-blink-commands` (just set it to nil).

**Comment by Knusper** [comment]
OK - right. I should have inspected that variable first..
