### ISSUE TITLE
Disable during edebug?

### ISSUE THREAD

**Issue by kaushalmodi** [Malabarba/beacon#22]
Hi,

Would it be a good idea to disable beacon when `edebug-active` is `t`?

Because right now, the beacon flashes as the cursor jumps to the next form as I hit `SPC` during edebug.

**Comment by Malabarba** [comment]
Yes, I think that makes sense.

**Comment by Malabarba** [comment]
BTW, for the moment, you can configure this manually with `beacon-dont-indent-hook`.

**Comment by Malabarba** [comment]
Nevermind. This was fixed by a recent push regarding false-positives in window-scroll-functions

**Comment by kaushalmodi** [comment]
Thanks!
