### ISSUE TITLE
Allow beacon to blink only on lines moving (vertical), not horizontal

### ISSUE THREAD

**Issue by ReneFroger** [Malabarba/beacon#23]
After upgrading Beacon to the latest master branch from MELPA, I noticed something was changed.

When I move a specific amount of lines down of up, the cursor will blink with beacon. Now it's also blinking when I move a specific amount of words forward or backwards.

I wouldn't do that. Is there any way to disable that?

**Comment by Malabarba** [comment]
That's really not supposed to happen. Does it happen absolutely anywhere for you?

**Comment by ReneFroger** [comment]
After reading your comment, I restarted Emacs. Now it doesn't happen anymore... I don't know why it occured. Weird... then I consider this issue as closed.. but it's still weird.

**Comment by ReneFroger** [comment]
I got the same issue again. See this screencast.

![beacon](https://cloud.githubusercontent.com/assets/5211845/10715297/dbbbf1ee-7b11-11e5-9764-1db2e9fe18b7.gif)

This is after startup Emacs by the way. What do I need in order to figure out what went wrong?

**Comment by Malabarba** [comment]
First, try disabling some of the minor-modes that have to do with scrolling, point-movement, or windows.
For instance, I see you have smooth-scroll enabled, that could possibly be a cause.

If that doesn't point to anything, let me know what values you have for `pre-command-hook` and `post-command-hook`.

**Comment by ReneFroger** [comment]
Disabling smooth scrolling and other minor modes related to point-movement and windows didn't help.

And the values for `pre-command-hook`:

    Its value is
    (company-pre-command evil-jump-hook eldoc-pre-command-refresh-echo-area t)

    Local in buffer *scratch*; global value is 
    (sp--pre-command-hook-handler sp--save-pre-command-state evil-repeat-pre-hook beacon--vanish tooltip-hide eldoc-pre-command-refresh-echo-area)

Then the values for `post-command-hook`:

    Its value is
    (evil-normal-post-command company-post-command yas--post-command-handler eldoc-schedule-timer t)

    Local in buffer *scratch*; global value is 
    (elscreen-run-screen-update-hook global-font-lock-mode-check-buffers global-adaptive-wrap-prefix-mode-check-buffers global-undo-tree-mode-check-buffers evil-mode-check-buffers global-evil-matchit-mode-check-buffers global-evil-visualstar-mode-check-buffers projectile-global-mode-check-buffers yas-global-mode-check-buffers vimish-fold-global-mode-check-buffers smartparens-global-mode-check-buffers imagex-global-sticky-mode-check-buffers global-anzu-mode-check-buffers global-edit-server-edit-mode-check-buffers global-company-mode-check-buffers sp--post-command-hook-handler twittering-reset-unread-status-info-if-necessary sml/generate-position-help evil-repeat-post-hook beacon--post-command eldoc-schedule-timer)

Is this perhaps useful for you to say anything about it?

**Comment by Malabarba** [comment]
Maybe. Is it solved if you disable evil-mode?

**Comment by Malabarba** [comment]
I also just pushed some code which may solve your issue. It should go up on Gelpa tomorrow.

**Comment by ReneFroger** [comment]
I don't see this issue happening again, so I consider this issue as solved. Thanks for your support Artur!
