### ISSUE TITLE
Disable blink during vertical scroll

### ISSUE THREAD

**Issue by holocronweaver** [Malabarba/beacon#25]
For whatever reason, setting `beacon-blink-when-window-scrolls nil` seems to have no effect. When I scroll using `scroll-up-command` it still blinks. Restarting emacs had no effect. Using beacon `20151025.828` from melpa.

**Comment by Malabarba** [comment]
Silly oversight on my part. Should be easy to fix.

**Comment by Malabarba** [comment]
Fixed

**Comment by holocronweaver** [comment]
A much delayed thanks. Fix works for me!
