### ISSUE TITLE
Trigger beacon on recentering commands

### ISSUE THREAD

**Issue by bbatsov** [Malabarba/beacon#31]
It'd be nice if commands like `recenter-top-bottom` (aka `C-l`) also triggered beacon's feedback.

**Comment by Malabarba** [comment]
I disabled it by default because I found it distracting. See the dont-blink-commands variable. 

You're not the first to ask, so I might re-enable eventually.

**Comment by Malabarba** [comment]
I think it's enabled now. Either way, this issue can be closed.
