### ISSUE TITLE
Beacon gives "mark set" message when scrolling

### ISSUE THREAD

**Issue by ReneFroger** [Malabarba/beacon#32]
Every time when I do a scroll action (Page up, page down), I get the following message in the minibuffer

      Mark set

After bisecting my Emacs configuration, it turned out I get this message when beacon-mode is enabled. 
I could never figure out why this message is popping up when beacon-mode is enabled. 

Emacs version is (latest snapshot for ubuntu):

       GNU Emacs 25.0.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.16.7) of 2015-10-28

And setup of Beacon is:

      (beacon-mode 1)
      (setq beacon-dont-blink-major-modes (quote (magit-status-mode dired-mode eshell-mode))
        beacon-blink-delay 0.2 
        beacon-blink-duration 0.2
        beacon-blink-when-point-moves 7
        beacon-blink-when-window-changes nil
        beacon-blink-when-window-scrolls nil
        beacon-color "brown"
        beacon-push-mark 5
        beacon-size 25)

Any suggestion why I get the message "Mark set"?

**Comment by Malabarba** [comment]
The message happens when beacon calls `push-mark`. I've changed it to be silent now. Should be on Gelpa tomorrow.

**Comment by ReneFroger** [comment]
Thanks for your reply. What does push-mark do, actually?

[sup]By the way, why seems Melpa called as Gelpa nowadays?[/sup]

**Comment by Malabarba** [comment]
> Thanks for your reply. What does push-mark do, actually?

It pushes the current position to the mark-ring. For instance, isearch uses it to save the place where you started the search. Then you can use `C-u SPC` to go back to previous places saved on the mark-ring.

Beacon provides a way to save current position to the mark ring whenever you move a long distance, that's what the `beacon-push-mark` variable is for.

>  By the way, why seems Melpa to be called as Gelpa nowadays?

It's not. :-)
I was referring to GNU Elpa.

**Comment by Malabarba** [comment]
Should be fixed now.
