### ISSUE TITLE
wrong-type-argument stringp nil

### ISSUE THREAD

**Issue by jonathanchu** [Malabarba/beacon#34]
Hey @Malabarba!  First off, great tool you wrote here - I've already noticed a difference in not searching around for my cursor so much when navigating files.

I seem to be encountering an issue now whenever beacon is working.  I have `(setq debug-on-error t)` in my config, which produces the following constantly:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("\\`unspecified-" nil)
  beacon--color-range()
  beacon--shine()
  beacon-blink()
  beacon--window-scroll-function(#<window 3 on init.el> 9862)
  redisplay_internal\ \(C\ function\)()
```

My config is exactly the same as from your [beacon post](http://endlessparentheses.com/beacon-never-lose-your-cursor-again.html), but used with `use-package`.  This was also installed via MELPA.

Let me know if I can help provide anymore info.  I had to disable beacon temporarily :-/

**Comment by Malabarba** [comment]
Sorry about that. Should be fixed now.

**Comment by jonathanchu** [comment]
No need to apologize at all! Thanks for the quick fix - all seems to be good now :+1: :beers:
