### ISSUE TITLE
`beacon-blink-when-point-moves-vertically` should respect scrolling via `next-page` and `previous-page`

### ISSUE THREAD

**Issue by waymondo** [Malabarba/beacon#35]
This package is great! I was doing something similar in my `.emacs.d` extending the built-in `pulse` package, but this is much nicer and cleaner implementation.

I'm noticing though that when I'm scrolling via `next-page` / `previous-page` (<kbd>C-n</kbd> / <kbd>C-p</kbd>) and I go under the threshold of my `scroll-margin` so that the window starts scrolling, beacon will trigger on each new line, regardless of the value of `beacon-blink-when-point-moves-vertically`.

Here are the values of my scrolling customizations for reference:

```elisp
(setq scroll-margin 24
      scroll-conservatively 10000
      scroll-preserve-screen-position 'always
      auto-window-vscroll nil)
```

**Comment by manuel-uberti** [comment]
Yes, same happens to me.

**Comment by Malabarba** [comment]
`beacon-blink-when-point-moves-vertically` only toggles blinking triggered by point movement. What you're seeing is blinking triggered by window-scroll.

You can disable that completely with `beacon-blink-when-window-scrolls`, but you probably don't want to do that.

I think the best answer here is to do:

    (add-to-list 'beacon-dont-blink-commands 'next-line)
    (add-to-list 'beacon-dont-blink-commands 'previous-line)

I may end up making this the default.

**Comment by manuel-uberti** [comment]
Yes, it works for me. Thank you!

**Comment by waymondo** [comment]
Thanks for the explanation and the solution. I think it makes sense to disable `next-line` and `previous-line` by default, but its easy enough to disable through customization.
