### ISSUE TITLE
Feature request: be able to pulse beacon on command

### ISSUE THREAD

**Issue by danrharms** [Malabarba/beacon#40]
I would like to make a request for a feature I didn't see, apologies if I missed it.  It would be nice to be able to have an interactive command that allows the user to pulse the beacon at any time, even without buffer movement.

This would be similar to functionality offered by 'hi-line-flash or 'crosshairs-flash.

Thank you.

**Comment by cpitclaudel** [comment]
Doesn't `beacon-blink` do that?

**Comment by danrharms** [comment]
Based on its description, yes, however calling it doesn't do anything for me.

**Comment by Malabarba** [comment]
Yeah, it's a small bug in the implementation. It's one of the things I'll fix once I'm back from holidays.

**Comment by cpitclaudel** [comment]
:)

**Comment by Malabarba** [comment]
Should be possible to call `beacon-blink` now, both as a command and from elisp.
The update will be on Gelpa when it rebuilds.

**Comment by cpitclaudel** [comment]
Indeed, works fine :) Though beacon-blink is still conditional on `beacon-mode`, right?

**Comment by Malabarba** [comment]
True. I've fixed that too on the latest push. :+1:

**Comment by cpitclaudel** [comment]
:)

**Comment by danrharms** [comment]
Works well, thank you.
