### ISSUE TITLE
Unable to install in Emacs 25

### ISSUE THREAD

**Issue by cpitclaudel** [Malabarba/beacon#41]
Hey Arthur,

Do you have any idea why package.el would complain that `seq` is not installable in Emacs 25 (the `emacs-25` branch)?

```
beacon is an incompatible package.

     Status: Incompatible because it depends on uninstallable packages.
    Archive: gnu

    Version: 0.5.1
    Summary: Highlight the cursor whenever the window scrolls
   Requires: seq-1.11 (not available)
   Homepage: https://github.com/Malabarba/beacon
   Keywords: convenience 
```

```
beacon is an incompatible package.

     Status: Incompatible because it depends on uninstallable packages.
    Archive: melpa

    Version: 20151205.1003
    Summary: Highlight the cursor whenever the window scrolls
   Requires: seq-1.11 (not available)
   Homepage: https://github.com/Malabarba/beacon
   Keywords: convenience 
```

All I do have is `seq                1.8           built-in              Sequence manipulation functions` in the list of packages (but not 2.3 as suggested in https://github.com/milkypostman/melpa/commit/76b7b90da2b4a1aef8ccb7aebe6dd335de612d7e).

**Comment by Malabarba** [comment]
That's very strange. Emacs 25 has a bundled version of seq. Maybe if you update to a more recent snapshot?

**Comment by cpitclaudel** [comment]
I'm using the lastest master on emacs-25. I did `make-clean`, then ran `emacs -Q` and `M-x list-packages`. `seq` is listed as version 1.8.

How I could debug this?

**Comment by cpitclaudel** [comment]
`make finder-data` did the trick; hat tip to @iqbalansari.

**Comment by Malabarba** [comment]
Damn. I've never run into anything like that. I was preparing a complicated response about how to debug this, but I'm glad to see you've solved it. 😀
