### ISSUE TITLE
`beacon-blink-when-buffer-changes` seems to not be used

### ISSUE THREAD

**Issue by asok** [Malabarba/beacon#43]
Hi, I wanted the beacon to blink when I switch buffers also. I see that there's a variable `beacon-blink-when-buffer-changes` in the code but it seems it is not used.
Shouldn't it be used in `beacon--post-command`?

I use version `20160206.917` from melpa.

**Comment by Malabarba** [comment]
Oops. Silly mistake.
Thanks for catching that.
