### ISSUE TITLE
Symbol's function definition is void: seq-do, only in Emacs 25

### ISSUE THREAD

**Issue by novakboskov** [Malabarba/beacon#45]
I have both Emacs versions, 24.5.3 and 25.1.50.2.
In v24 beacon is loaded well and everything is working good.
In v25 there is `Symbol's function definition is void: seq-do`.
My `seq.el` version listed in `package-list-packages` is latest (2.15).
I've also tried to start without `init.el`  using `emacs -q` and then tried:
`(require 'seq)` and then `M-x describe-function seq-do` and it shows the documentation which means that it is loaded.
Also, `beacon` is not the only package that suffers with this, `flycheck` have the same struggle.

**Comment by Malabarba** [comment]
I've bumped the seq dependency. Let me know if that solves it.

**Comment by novakboskov** [comment]
No, it's the same.

Beacon version is `20160404.608`

**Comment by Malabarba** [comment]
Try deleting your seq package and reinstalling it from Emacs 24.
It's a dangerous game you're playing by using the same packages directory (`.emacs.d/elpa/`) under different emacs versions. :-)

**Comment by novakboskov** [comment]
Why to reinstall from Emacs 24 when problem occurs in v25?
At first I've tried to do as you said and it didn't worked, then I've tried to reinstall from Emacs 25 and now it looks like everything is fine.
Why my setup is dangerous? Do you have some reading to recommend me?
Thanks for help.

**Comment by Malabarba** [comment]
The byte-compiler doesn't generally try to be backwards compatible in its output.
That is, code compiled in Emacs 25 has no guarantees that it'll run on Emacs 24, even if the uncompiled code was compatible with both 24 and 25.

In addition, some packages define different functions/macros depending on what Emacs version they were compiled in. `seq` is one such package, but there are many others. So if you compile it in one Emacs version, there might be missing definitions when you run it on another Emacs version.

**Comment by novakboskov** [comment]
It makes sense. And it implies that working state of my setup is more like pure luck.

**Comment by Malabarba** [comment]
:-)
