### ISSUE TITLE
Beacon not active when point moves.

### ISSUE THREAD

**Issue by johanvts** [Malabarba/beacon#46]
I have this in my init file:

(beacon-mode 1)
(setq beacon-blink-when-point-moves-vertically 1)
(setq beacon-blink-when-point-moves-horizontally 1)

Yet, the beacon only shows when I scroll. I would like it to show up any time I move the cursor using the arrow keys. Not sure if I'm missing something or this is a genuine bug.

**Comment by Malabarba** [comment]
Hm. I think the vertical movement is a little buggy, but the horizontal movement works fine for me.

Keep in mind that the value is compared with `>`, not `>=`, so you would have to set them to `0` to get the behaviour you want.

**Comment by Malabarba** [comment]
Ah. You'll also have to remove the symbols `next-line` and `previous-line` from the variable `beacon-dont-blink-commands`.

**Comment by Malabarba** [comment]
Do the above suggestions work for you?

**Comment by johanvts** [comment]
It works better, the cursor will not blink if I move up and down at the beginning of a line, but from the middle of a line it works.

**Comment by Malabarba** [comment]
That sounds like a different bug. Could it be some other package is conflicting with beacon?
