### ISSUE TITLE
Please tag latest commit

### ISSUE THREAD

**Issue by DamienCassou** [Malabarba/beacon#48]
Could you please tag the current commit so that your package appears on melpa stable? You can do it through github in the "releases" tab or through `git tag`. Thanks

**Comment by DamienCassou** [comment]
any news?

**Comment by Malabarba** [comment]
Hi Damien, sorry I forgot to reply to  your previous message. 
Beacon already has stable releases on Gnu Elpa, is there any reason you need this to be on Melpa stable? 

Of course, it wouldn't be any trouble to tag this now, but I'd probably keep forgetting to tag future releases. Truth is, I don't even know who put Beacon on Melpa.

**Comment by DamienCassou** [comment]
Sorry, I just didn't check Gnu Elpa. Thanks.
