### ISSUE TITLE
beacon-blink not blinking the beacon when called from emacs-lisp

### ISSUE THREAD

**Issue by qazmonk** [Malabarba/beacon#49]
I am making a small script that should blink beacon as a part of it's execution. I can run 'M-x beacon-blink' and the beacon blinks but if evaluating the function call (beacon-blink) produces no output. Is there a special way I should be calling that function that is different from running the command?

**Comment by Malabarba** [comment]
Thanks for reporting. SHould be fixed now.

**Comment by qazmonk** [comment]
Thank you!
