### ISSUE TITLE
Doesn't work with mode-icons

### ISSUE THREAD

**Issue by rsbowman** [Malabarba/beacon#53]
When [mode-icons mode](https://github.com/ryuslash/mode-icons) is on, the beacon stays around until I insert a character or M-x.  Very occasionally it disappears on its own.  Thanks for any help you could offer in debugging this issue.

Very cool package, thanks!

**Comment by Malabarba** [comment]
That's odd. =/
Unfortunately, I don't have the time right now to look into why the two packages are conflicting. Maybe we can ask the authors of mode-icons for help here. :)

Beacon disappears by running on a timer that slowly reduces its length (and by having a before-command-hook that destroys it completely). I''ve no idea why mode-icons might conflict with that.

**Comment by rsbowman** [comment]
Me either.  I'll ask over there.  Thanks for the help!
