### ISSUE TITLE
Release on elpa

### ISSUE THREAD

**Issue by DamienCassou** [Malabarba/beacon#54]
Despite your 1.3.2 release, gnu elpa still advertises 1.3.1 as latest. Could you please fix that?

**Comment by Malabarba** [comment]
Will do tonight. Give me a shout if I forget. :stuck_out_tongue_closed_eyes:

**Comment by Malabarba** [comment]
Ok, I forgot. I swear I'll do it tonight. :-(

**Comment by DamienCassou** [comment]
I'm starting to doubt it :-). I will throw tomatoes at you on [Thursday](http://www.meetup.com/Stockholm-Emacs-Meetup/events/234588339/)! /cc @NicolasPetton

**Comment by NicolasPetton** [comment]
Damien Cassou <notifications@github.com> writes:

> I'm starting to doubt it :-). I will throw tomatoes at you on
> [Thursday](http://www.meetup.com/Stockholm-Emacs-Meetup/events/234588339/)!
> /cc @NicolasPetton

I'll be there to witness it.

**Comment by Malabarba** [comment]
Well, Nico might be upset if you start throwing tomatoes at a projector screen. :-)

I don't have my ssh credentials setup at work alright?! I can even pull Elpa or Emacs there anymore.
I've pushed the changes now. Just please hold the vegetables until Elpa rebuilds.

**Comment by DamienCassou** [comment]
Thank you very much.
