### ISSUE TITLE
Beacon stays active in dired-mode

### ISSUE THREAD

**Issue by vmalloc** [Malabarba/beacon#55]
I have beacon enabled in my config:
```
 (use-package beacon
  :ensure t
  :config
  (beacon-mode 1)
  (setq beacon-color "cyan"))
```

When I open a directory with dired, the beacon stays active and does not disappear...

**Comment by vmalloc** [comment]
Seems to be only a specific setup. Will investigate further

**Comment by Malabarba** [comment]
Sure. Let me know if you figure out what the problem was.

**Comment by Kaali** [comment]
This happens to me when using dired through TRAMP.
