### ISSUE TITLE
Last commit breaks format-spec

### ISSUE THREAD

**Issue by DamienCassou** [Malabarba/beacon#60]
This should be `t`

```emacs
(string= (format-spec "%s" '((?s . "foo"))) "foo")
```

but triggers an error with latest beacon commit.

**Comment by DamienCassou** [comment]
The error is:

```
Args out of range: #<killed buffer>, 3, 10
```

**Comment by dakra** [comment]
Took me a bit to find what broke my Emacs yesterday as well. see https://github.com/Malabarba/beacon/issues/57

**Comment by Malabarba** [comment]
I see what I did wrong, but it's a little odd that this problem never showed up before (the string-match was there already, I just changed the regex).

Anyway, should be fixed on the next build.
