### ISSUE TITLE
not able to customize beacon color

### ISSUE THREAD

**Issue by dpsutton** [Malabarba/beacon#9]
I was trying to customize the beacon color with M-x customize-group. The instructions for doing so are "
If it is a string, it is a color name or specification,
e.g. \"#666600\"."".

However, when i try to enter "blue" or even your suggestion of "#666600", I get a warning at the bottom that "Saving beacon-color: This field should contain a number (floating point or integer)". I tried to change the types on (defcustom beacon-color   :type '(choice number color)) but changing color to string left me no better off.
<img width="717" alt="screen shot 2015-10-16 at 4 47 59 pm" src="https://cloud.githubusercontent.com/assets/6377293/10554152/905e9946-7426-11e5-884e-be6c878ebd4e.png">

**Comment by Malabarba** [comment]
You need to click on the `Value Menu` button and change the value type.
Since you closed the issue, I guess you already figured that out?

**Comment by dpsutton** [comment]
I did and was hoping it would not bother you with such a trivial and easily solved problem. I really enjoy your package and am reading through it learning now it works. Your coding style and documentation is quite enjoyable. This seems like a perfect tutorial package in how to design something really well, including customize group menus, documentation, and clarity of style.

**Comment by Malabarba** [comment]
Glad to know that. ☺
