### ISSUE TITLE
Is ther a way to achieve neovide-like cursor move animation in Emacs?

### ISSUE THREAD

**Issue by suliveevil** [Malabarba/beacon#91]
https://github.com/neovide/neovide

Neovide's visual indicator is awesome! Is ther a way to achieve neovide like cursor-move animation in Emacs?

**Comment by antler5** [comment]
I think I've spent enough time crawling around the C rendering code to say "no": There is no reasonable approach for achieving this within a loadable elisp package. If there is, it will be a hack with unacceptable compromises on robustness, performance, and/or maintainability. One could conceivably fork this into Emacs, and _maybe?_ package those changes into a [Dynamic Module](https://www.gnu.org/software/emacs/manual/html_node/elisp/Dynamic-Modules.html), but it would intersect with many existing systems and present a serious challenge well beyond the scope and nature of this package.

That said the cursor is pretty awesome, and maybe someone will consider the challenge worth approaching; thanks for suggesting it c:

**Comment by suliveevil** [comment]
Thank you very much.
